OC\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: OC\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        salt:
            type: array
        roles:
            type: array
    lifecycleCallbacks: {  }
